### ISSUE TITLE
Game Won't Launch

### ISSUE THREAD

**Issue by DaFluffyPotato** [Shirakumo/ld39#1]
I was running it off of a flash drive because I didn't have enough hard drive space to run it(not sure if this is important). I tried to run it and it briefly pops up in task manager processes then disappears.

**Comment by Shinmera** [comment]
Flash drive or not shouldn't be important from what I know. What OS & version is this?

**Comment by gingeralesy** [comment]
This happened on the Windows 64 build.

**Comment by Shinmera** [comment]
That still doesn't tell me which version of Windows.
Anyway- I won't be able to figure out much without some debug information. To obtain it, run a command prompt, navigate to the folder the `ld39.exe` is in and run it as follows:

```batch
set DEPLOY_REDIRECT_OUTPUT=output.txt
ld39.exe
```

Once the application ends, open the output.txt in the same folder and paste the contents here.

**Comment by Shinmera** [comment]
Right now I'm guessing that it crashes because it can't access some GL functions.

**Comment by Shinmera** [comment]
@DaFluffyPotato Actually, [here](https://filebox.tymoon.eu//file/TVRNNE1nPT0=)'s a new binary that will automatically produce a `trial.log` file for you. If you could use that instead and send us the log, that would be great.

**Comment by DaFluffyPotato** [comment]
I was borrowing a computer when that happened and I no longer have access to it, so I don't think I can help anymore. :/
(the computer I was using was super cheap)

**Comment by Shinmera** [comment]
Okey. Very likely that OpenGL wasn't good enough then. Thanks anyway.
